# Site settings
title: Bruno Henriques

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bphenriques.github.io" # the base hostname & protocol for your site

author:
    fullname: Bruno Henriques
    profile-image: "https://lh3.googleusercontent.com/4sR4lWUfxfndLPRPtTXjCLa5WLUu9SF_o-nvLc2zJxRo0eNzi5RMPbOXsBNzwKQNsUZJ=w6720-h4200-rw-no"
    email: brunoaphenriques@gmail.com
    linkedin: bphenriques
    github: bphenriques
    instagram: brunophenriques
    skype: bruno.h31    
    #twitter: electrik_frog
    #twitch: 
    #tumblr: 
    #steam: 
    #spotify:
    #stack-overflow: 
    #reddit:

disqus: :bphenriquesgithubio
google_analytics: 'UA-74411247-1'


###                            #####
### Social build configuration #####
###                            #####

social-base-url:
    email: "mailto:"
    google-plus: https://plus.google.com/u/0/
    linkedin: https://pt.linkedin.com/in/
    github: https://github.com/
    youtube: https://www.youtube.com/channel/
    instagram: https://www.instagram.com/
    twitter: https://twitter.com/
    skype: "skype:"

social-end-url:
    skype: "?add"

custom-fav-icon:
    email: envelope


###                            #####
###    Build configurations    #####
###    Do not change below     #####
###                            #####


# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown

sitemap:
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "README.md"
        - "README.html"

gems: 
  - jekyll-mentions
  - jemoji
  - jekyll-feed
  - jekyll-sitemap